version = "0"
full_text = """{{index .Lines "1-1"}}
{{index .Lines "1-2"}}
{{index .Lines "1-3"}}

{{index .Lines "11-1"}}
{{index .Lines "11-2"}}
{{index .Lines "11-3"}}"""
translation = """
おお、息子たちよ、娘たちよ、
天の王は、栄光の王は
死から今日復活した。アレルヤ。

この最も聖なる祭において
賞賛と歓喜がありますように。
主を讃えよう。アレルヤ。"""
[lines]
1-1 = "Ō fīliī et fīliae,"
1-2 = "Rex caelestis, Rex glōriae,"
1-3 = "morte surrexit hodiē, allēlūia."
11-1 = "In hōc festō sanctissimō"
11-2 = "sit laus et jūbilātiō,"
11-3 = "benedīcāmus Dominō, allēlūia."

[[nouns]]
original_form = "fīlius"
declension_type = 2
translation = "息子"
explanation = "fīlius,fīliī m."
declensions = {"vmp" = "fīliī"}
[[nouns]]
original_form = "fīlia"
declension_type = 1
translation = "娘"
explanation = "fīlia,fīliae f."
declensions = {"vfp" = "fīliae"}
[[nouns]]
original_form = "rex"
declension_type = 3
translation = "王"
explanation = "rex,rēgis m."
declensions = {"1m" = "rex"}
[[nouns]]
original_form = "glōria"
declension_type = 1
translation = "栄光"
explanation = "glōria,glōriae f."
declensions = {"2f" = "glōriae"}
[[nouns]]
original_form = "mors"
declension_type = 3
translation = "死"
explanation = "mors,mortis f."
declensions = {"af" = "morte"}
[[nouns]]
original_form = "festum"
declension_type = 2
translation = "祝祭"
explanation = "festum,festī n."
declensions = {"an" = "festō"}
[[nouns]]
original_form = "laus"
declension_type = 3
translation = "賞賛"
explanation = "laus,laudis f."
declensions = {"1f" = "laus"}
[[nouns]]
original_form = "jūbilātiō"
declension_type = 3
translation = "歓喜"
explanation = "jūbilātiō,-ōnis f."
declensions = {"1f" = "jūbilātiō"}
[[nouns]]
original_form = "dominus"
declension_type = 2
translation = "主"
explanation = "dominus,dominī m."
declensions = {"3m" = "dominō"}

[[adjs]]
original_form = "caelestis"
declension_type = 3
translation = "天の"
explanation = "caelestis,-stis"
declensions = {"1m" = "caelestis"}

[[verbs]]
original_form = "surgō"
conjugation_type = 3
translation = "立ち上がる、復活する"
explanation = "surgō,surgere"
[verbs.conjugations]
"ind/perf" = {"3s" = "surrexit"}
[[verbs]]
original_form = "sum"
conjugation_type = 0
translation = "ある、いる"
explanation = "sum,esse"
[verbs.conjugations]
"sub/pres" = {"3s" = "sit"}
[[verbs]]
original_form = "benedīcō"
conjugation_type = 3
translation = "讃える"
explanation = "benedīcō,-ere"
[verbs.conjugations]
"sub/pres" = {"1p" = "benedīcāmus"}

[[preps]]
original_form = "in"
translation = "〜〜へ/〜〜で"
takes = "4a"
