version = "0"
full_text = """{{index .Lines "1-1"}}
{{index .Lines "1-2"}}
{{index .Lines "1-3"}}
{{index .Lines "1-4"}}
{{index .Lines "1-5"}}

{{index .Lines "2-1"}}
{{index .Lines "2-2"}}"""
translation = """聖なる三位一体が祝福されますように。
そして不可分な結束も。
私たちは彼を認めるだろう。
なぜなら彼は私たちとともに慈悲を与えたからだ。

私たちは父と子を、聖霊とともに祝福しよう。"""

[lines]
1-1 = "Benedicta sit sancta Trīnitās"
1-2 = "atque indīvīsa Ūnitās"
1-3 = "confitēbimur eī"
1-4 = "quia fēcit nōbiscum misericordiam suam."
1-5 = "Allēlūia."
2-1 = "Benedīcāmus Patrem et Fīlium"
2-2 = "cum Sanctō Spīritū."

[[nouns]]
original_form = "trīnitās"
declension_type = 3
translation = "三位一体"
explanation = "trīnitās,-tis f."
declensions = {"1f" = "trīnitās"}
[[nouns]]
original_form = "ūnitās"
declension_type = 3
translation = "結束"
explanation = "ūnitās,ūnitātis f."
declensions = {"1f" = "ūnitās"}

[[verbs]]
original_form = "benedīcō"
conjugation_type = 3
translation = "讃える"
explanation = "benedīcō,-ere"
[verbs.conjugations]
"sub/pres" = {"1p" = "benedīcāmus"}
